### ISSUE TITLE
add code of conduct

### ISSUE THREAD

**Issue by YHuUBC** [UBC-MDS/easyphysics#9]

**Comment by YHuUBC** [comment]
Code of conduct has been automatically created with cookie-cutter:

https://github.com/UBC-MDS/easyphysics/blob/main/CONDUCT.md

**Comment by revathyponn** [comment]
Yes, are we going to use the same or we are going to add some attributions?

**Comment by YHuUBC** [comment]
Good point, let's add some attributions here and there.

**Comment by YHuUBC** [comment]
stick to the default CONDUCT generated by cookiecutter
